<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="You security platform.">
    <meta name="author" content="Detectlry Factory">

    <title><?! Language::get('welcome.title') ?></title>
    
    <!-- CSS -->
    [% stylesheet app %]

    <!-- Links -->
    <link rel="shortcut icon" href="<?! HTML::url('assets/images/favicon.ico') ?>" type="image/x-icon"/>
    <link rel="alternate" type="application/rss+xml" title="" href="/feed.xml">
    <link rel="canonical" href="http://deftcode.ninja/">

    <!-- Fonts -->
    <link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>